{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bdgz.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "bdgz.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}
  {{- end }}
  selector:
    matchLabels: {{- include "bdgz.selectorLabels" . | nindent 6 }}
{{- end }}
