{{- if eq (include "bdgz.createAuthSecret" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bdgz.authSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "bdgz.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "bdgz.authSecretKey" . }}: {{ .Values.auth.value | quote }}
{{- end }}
