apiVersion: v1
kind: Service
metadata:
  name: {{ include "bdgz.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bdgz.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- if and (ne .Values.service.type "ClusterIP") (ne .Values.service.type "ExternalName") .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  selector: {{- include "bdgz.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: api
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
